// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6ldl29viXV20dST73luY37C1eC3VZSk',
    appId: '1:675666269735:web:be8599db3207c7af802002',
    messagingSenderId: '675666269735',
    projectId: 'esi-pf-project',
    authDomain: 'esi-pf-project.firebaseapp.com',
    storageBucket: 'esi-pf-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6ldl29viXV20dST73luY37C1eC3VZSk',
    appId: '1:675666269735:android:be8599db3207c7af802002',
    messagingSenderId: '675666269735',
    projectId: 'esi-pf-project',
    storageBucket: 'esi-pf-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcR5ZJMvndszpkTH0OQj9i2u3jB5VplCQ',
    appId: '1:675666269735:ios:6c63caed971ed185802002',
    messagingSenderId: '675666269735',
    projectId: 'esi-pf-project',
    storageBucket: 'esi-pf-project.firebasestorage.app',
    iosBundleId: 'com.example.esiPfProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcR5ZJMvndszpkTH0OQj9i2u3jB5VplCQ',
    appId: '1:675666269735:ios:6c63caed971ed185802002',
    messagingSenderId: '675666269735',
    projectId: 'esi-pf-project',
    storageBucket: 'esi-pf-project.firebasestorage.app',
    iosBundleId: 'com.example.esiPfProject',
  );
}
